CREATE DATABASE SocialNetwork;

USE SocialNetwork;

CREATE TABLE Users (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    FirstName NVARCHAR(50),
    LastName NVARCHAR(50),
    Email NVARCHAR(100) UNIQUE,
    Password NVARCHAR(100),
    RegisteredDate DATETIME DEFAULT GETDATE()
);

CREATE TABLE Relationships (
    UserID INT FOREIGN KEY REFERENCES Users(UserID),
    FriendID INT FOREIGN KEY REFERENCES Users(UserID),
    Status BIT DEFAULT 0,
    PRIMARY KEY (UserID, FriendID)
);

CREATE TABLE Dialogs (
    DialogID INT PRIMARY KEY IDENTITY(1,1),
    UserID INT FOREIGN KEY REFERENCES Users(UserID),
    FriendID INT FOREIGN KEY REFERENCES Users(UserID),
);

CREATE TABLE Messages (
    MessageID INT PRIMARY KEY IDENTITY(1,1),
    DialogID INT FOREIGN KEY REFERENCES Dialogs(DialogID),
    SenderID INT FOREIGN KEY REFERENCES Users(UserID),
    ReceiverID INT FOREIGN KEY REFERENCES Users(UserID),
    MessageContent NVARCHAR(500),
    SentDate DATETIME DEFAULT GETDATE()
);